indentation fixed
trent-soloman/sprint-2 pull request #1
Opened 2016-10-04 00:49 UTC by trent-soloman

Indentation done.

2016-10-06 23:04 UTC, JessicaNeary requested changes

2016-10-06 23:04 UTC, JessicaNeary commented on pristine-zen-garden.html
> +              </li>         <li>
Hi Trent, I think your list indentation still needs to be adjusted so each list tag is on it's own line. Also you might want to tidy up your whitespace a little bit, one convention you can use it to have one space between each tag, two spaces between related sections of tags and three or more spaces between unrelated sections.

2016-10-08 03:54 UTC, trent-soloman commented on pristine-zen-garden.html
> +              </li>         <li>
Ok.

2016-10-09 00:40 UTC, nat-sei-ava commented
I see that trent has actioned indentation request and have merged.

2016-10-09 00:41 UTC, merged